### ISSUE TITLE
Cannot list new CRD resources

### ISSUE THREAD

**Issue by ayj** [istio/pilot#1107]
kubectl cannot list the the new CRD resources.

```bash
$ kubectl get route-rules.config.istio.io                                                                                                                                                                                                                      
the server doesn't have a resource type "route-rules" in group "config.istio.io"
```
Accessing the API server works as expected.

```bash
$ kubectl get route-rules.config.istio.io                                                                                                                                                                                                                       
the server doesn't have a resource type "route-rules" in group "config.istio.io"
```
IngressRule and DestinationPolicy have similar issues. The problem may be related to the naming convention with a `-` (route-rules vs. routerules). Using `routerules` instead of `route-rules` in the CRD produces the correct behavior (see below). This is possibly a kubectl bug since the apiserver returns the proper results.

```
cat << EOF | kubectl apply -f - 
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routerules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: RouteRule
    plural: routerules
    singular: routerule
  scope: Namespaced
  version: v1alpha2
EOF

customresourcedefinition "routerules.config.istio.io" created

$ cat << EOF | kubectl apply -f -
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routerules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: RouteRule
    plural: routerules
    singular: routerule
  scope: Namespaced
  version: v1alpha2
EOF
customresourcedefinition "routerules.config.istio.io" configured

$ kubectl get routerules.config.istio.io
NAME      KIND
rule0     RouteRule.v1alpha2.config.istio.io
```

**Comment by ayj** [comment]
/cc @andraxylia, @rshriram - you can use curl+python as a workaround to view the current rules, etc.

```bash
 curl -s localhost:8001/apis/config.istio.io/v1alpha2/route-rules | python -m json.tool
```

**Comment by ayj** [comment]
/cc @lavalamp, @caesarxuchao - is this expected kubectl behavior and we need to fix our definitions? 

For reference, here is the non-working CRD

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: route-rules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: RouteRule
    plural: route-rules
    singular: routerule
  scope: Namespaced
  version: v1alpha2
```
