### ISSUE TITLE
Do not add initContainer with cap `CAP_NET_ADMIN`

### ISSUE THREAD

**Issue by gyliu513** [istio/pilot#1161]
Now, we are adding `initContainer` with cap as `CAP_NET_ADMIN` https://github.com/istio/pilot/blob/master/platform/kube/inject/inject.go#L327 , this is not right, as docker will add `CAP` prefix again for the container again, this caused the pod creating failed.

Take the following example:

```
root@k8s001:~/cases/cap# cat cap.yaml
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-4
spec:
  containers:
  - name: sec-ctx-4
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        add: ["CAP_NET_ADMIN", "SYS_TIME"]
```

Create the pod
```
kubectl create -f ./cap.yaml
```

Pod creation failed
```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath			Type		Reason			Message
  ---------	--------	-----	----			-------------			--------	------			-------
  1m		1m		1	default-scheduler					Normal		Scheduled		Successfully assigned security-context-demo-4 to k8s001
  1m		1m		1	kubelet, k8s001						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-5j13j"
  1m		17s		5	kubelet, k8s001		spec.containers{sec-ctx-4}	Normal		Pulled			Container image "gcr.io/google-samples/node-hello:1.0" already present on machine
  1m		17s		5	kubelet, k8s001		spec.containers{sec-ctx-4}	Normal		Created			Created container
  1m		17s		5	kubelet, k8s001		spec.containers{sec-ctx-4}	Warning		Failed			Error: failed to start container "sec-ctx-4": Error response from daemon: linux spec capabilities: Unknown capability to add: "CAP_CAP_NET_ADMIN"
  1m		4s		11	kubelet, k8s001						Warning		FailedSync		Error syncing pod
  1m		4s		6	kubelet, k8s001		spec.containers{sec-ctx-4}	Warning		BackOff			Back-off restarting failed container
```
