### ISSUE TITLE
Add a new flag to sidecar initializer to config global annotation policy

### ISSUE THREAD

**Issue by gyliu513** [istio/pilot#1163]
There are three annotation policies in sidecar initializer,  now we cannot configure this parameter now, it is better add a parameter to enable user can set annotation policy.

```
        istioSidecarAnnotationPolicyValueDefault  = "policy.sidecar.istio.io/default"
	istioSidecarAnnotationPolicyValueForceOn  = "policy.sidecar.istio.io/force-on"
	istioSidecarAnnotationPolicyValueForceOff = "policy.sidecar.istio.io/force-off"
```

/cc @ayj comments? I can create a PR if you are ok for this.

**Comment by ayj** [comment]
Is this a request for kube-inject to insert the per-resource policy as part of injection? If so, wouldn't that be implied by the operator choosing (or not) to run kube-inject for that particular resource. In other words, don't run kube-inject on resources that shouldn't have a sidecar injected (or add the annotation as part of CI/CD pipeline).

**Comment by gyliu513** [comment]
We can launch an initializer as following for now.

```
ontainers:
        - name: sidecar-initializer
          image: {{.Hub}}/sidecar_initializer:{{.Tag}}
          imagePullPolicy: IfNotPresent
          args:
            - --port=8083
            - --namespace={{.IstioNamespace}}
            - -v=2
          volumeMounts:
          - name: config-volume
            mountPath: /etc/istio/config
```

I mean we can probably add a new parameter named as `annotaitonPolicy` for initializer,its value can be `off`, `opt-in` and `opt-out`, comments? @ayj

**Comment by gyliu513** [comment]
Close this one as we are now using `istio-inject` config map to define both `injectionPolicy` and `Namespaces` that is going to be monitor.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-inject
data:
  config: |-
    policy: {{.Policy}}
    namespaces:
{{ range $namespace := .Namespaces}}
    - {{$namespace}}
{{ end }}
    params:
      initImage: {{.Params.InitImage}}
      proxyImage: {{.Params.ProxyImage}}
      verbosity: {{.Params.Verbosity}}
      SidecarProxyUID: {{.Params.SidecarProxyUID}}
      Version: {{.Params.Version}}
      EnableCoreDump: {{.Params.EnableCoreDump}}
      MeshConfigMapName: {{.Params.MeshConfigMapName}}
      ImagePullPolicy: {{.Params.ImagePullPolicy}}
      IncludeIPRanges: {{.Params.IncludeIPRanges}}
```
