### ISSUE TITLE
Simplify initializer injection policy

### ISSUE THREAD

**Issue by ayj** [istio/pilot#1164]
### current
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    policy.sidecar.istio.io: policy.sidecar.istio.io/force-on
  name: my-deployment 
# etc ... 
```
### proposed
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    sidecar.istio.io/inject-override: true
  name: my-deployment 
# etc ... 
```

`sidecar.istio.io/inject-override` becomes a tristate boolean with the following semantics. 

```yaml
# Override default global policy and inject sidecar. Has no affect if global policy is `opt-out`.
sidecar.istio.io/inject-override: true

# Override default global policy and do not inject sidecar. Has no affect if global policy is `opt-in`.
sidecar.istio.io/inject-override: false

# No annotation (i.e. missing key) or unknown value results in default behavior.
```
