### ISSUE TITLE
model.Config ResolveHostname() always appends namespace

### ISSUE THREAD

**Issue by GregHanson** [istio/pilot#1179]
Creating the following rule yaml for a consul service with istioctl:
```type: route-rule
name: reviews-default
domain: service.consul
spec:
  destination:
    name: reviews
  precedence: 1
  route:
    - labels:
         version: v1
      weight: 75
    - labels:
          version: v2
      weight: 25
```

Results in the following rule 
```
{
    "type": "route-rule",
    "name": "reviews-default",
    "namespace": "default",
    "domain": "cluster.local",
    "resourceVersion": "71",
    "Spec": {
      "destination": {
        "name": "reviews"
      },
      "precedence": 1,
      "route": [
        {
          "labels": {
            "version": "v1"
          },
          "weight": 75
        },
        {
          "labels": {
            "version": "v2"
          },
          "weight": 25
        }
      ]
    }
  }
```

ResolveHostname() returns `reviews.default.svc.cluster.local` when the desired output should look like `reviews.service.consul`.  Consul, like Eureka, has no concept of namespace, and so it is not a factor in service conversion.

A temporary workaround is to define the rule as follows:
```
type: route-rule
name: reviews-default
spec:
  destination:
    name: reviews
    domain: consul
    namespace: service
  precedence: 1
  route:
    - labels:
         version: v1
      weight: 75
    - labels:
          version: v2
      weight: 25
```

**Comment by GregHanson** [comment]
Ideally I would expect to be able to define the rule as either:
```
type: route-rule
name: reviews-default
spec:
  destination:
    name: reviews
    domain: service.consul
```
Or
```
type: route-rule
name: reviews-default
domain: service.consul
spec:
  destination:
    name: reviews
```

**Comment by kyessenov** [comment]
The issue is that CRDs require non-empty namespace, which means every service inherits some namespace. 
Should we allocate a dedicated namespace for non-namespaced services? @mandarjog @frankbu

**Comment by frankbu** [comment]
Are you suggesting something like this:
```
type: route-rule
name: reviews-default
spec:
  destination:
    name: reviews
    domain: service.consul
    namepace: NONE
```
would produce hostname ` reviews.service.consul`?

I think something like that would work.

**Comment by rshriram** [comment]
Why can't we do `destination: reviews.service.consul` ? If I specify a fqdn in the source or destination name (one with dots), nothing should be inherited. Expecting users to null out namespace field in every mention of destination or source is not a great experience.

Trying to think of a way by which we don't require end users to specify namespace all over the place.

**Comment by frankbu** [comment]
We do have a `service` field in `IstioService`, so could we use it?
```
type: route-rule
name: reviews-default
spec:
  destination:
    service: reviews.service.consul
```

**Comment by kyessenov** [comment]
Yeah, I like the service field more. There is TODO to support it, so maybe it didn't work for Greg when he tried it.

**Comment by GregHanson** [comment]
@frankbu @kyessenov service field is not currently supported:
```
type: route-rule
name: content-route
spec:
  destination:
    service: reviews.service.consul
  match:
    request:
      headers:
        cookie:
          regex: ^(.*?;)?(user=jason)(;.*)?$
  precedence: 2
  route:
    - labels:
        version: v2
```
results in:
```
c$ istioctl create -f ../consul-content-route.yaml 
Error: cannot parse proto message: 1 error occurred:

* name is mandatory for a service reference
```
Even if I supply a `name` field, `service` field is not used in the ResolveHostname() logic, only domain and namespace
https://github.com/istio/pilot/blob/master/model/config.go#L323

and so the hostname check here fails during the rule/service matching because it always appends a domain and namespace to the hostname:
https://github.com/istio/pilot/blob/master/model/config.go#L398
