### ISSUE TITLE
Pilot CRDs left in the system after uninstall

### ISSUE THREAD

**Issue by andraxylia** [istio/pilot#1328]
Pilot CRDs need to be added to the yaml files so they can be removed if istio is uninstalled, similar to how mixer does it.

This is left after uninstall:
$ k get crd 
NAME                                  KIND
destinationpolicies.config.istio.io   CustomResourceDefinition.v1beta1.apiextensions.k8s.io
egressrules.config.istio.io           CustomResourceDefinition.v1beta1.apiextensions.k8s.io
routerules.config.istio.io            CustomResourceDefinition.v1beta1.apiextensions.k8s.io

istio/istio templates also need this change.

**Comment by ldemailly** [comment]
workaround in the meantime
```
kubectl get crd -o 'jsonpath={.items[*].metadata.name}'|grep config.istio.io |xargs kubectl delete crd
```
which will catch any leak too in case mixer would have extra etc

**Comment by kyessenov** [comment]
@andraxylia can you add this to installation:
```
apiVersion: apiextensions.k8s.io/v1beta1                                                                                                                      
kind: CustomResourceDefinition                                                                                                                                
metadata:                                                                                                                                                     
  name: destinationpolicies.config.istio.io                                                                                                                   
spec:                                                                                                                                                         
  group: config.istio.io                                                                                                                                      
  names:                                                                                                                                                      
    kind: DestinationPolicy                                                                                                                                   
    listKind: DestinationPolicyList                                                                                                                           
    plural: destinationpolicies                                                                                                                               
    singular: destinationpolicy                                                                                                                               
  scope: Namespaced                                                                                                                                           
  version: v1alpha2                                                                                                                                           
---                                                                                                                                                           
apiVersion: apiextensions.k8s.io/v1beta1                                                                                                                      
kind: CustomResourceDefinition                                                                                                                                
metadata:                                                                                                                                                     
  name: egressrules.config.istio.io                                                                                                                           
spec:                                                                                                                                                         
  group: config.istio.io                                                                                                                                      
  names:                                                                                                                                                      
    kind: EgressRule                                                                                                                                          
    listKind: EgressRuleList                                                                                                                                  
    plural: egressrules                                                                                                                                       
    singular: egressrule                                                                                                                                      
  scope: Namespaced                                                                                                                                           
  version: v1alpha2                                                                                                                                           
---                                                                                                                                                           
apiVersion: apiextensions.k8s.io/v1beta1                                                                                                                      
kind: CustomResourceDefinition                                                                                                                                
metadata:                                                                                                                                                     
  name: routerules.config.istio.io                                                                                                                            
spec:                                                                                                                                                         
  group: config.istio.io                                                                                                                                      
  names:                                                                                                                                                      
    kind: RouteRule                                                                                                                                           
    listKind: RouteRuleList                                                                                                                                   
    plural: routerules                                                                                                                                        
    singular: routerule                                                                                                                                       
  scope: Namespaced                                                                                                                                           
  version: v1alpha2 
```
